### ISSUE TITLE
suggest to remove "Bootstrap 4 snippets" as dependency + MORE

### ISSUE THREAD

**Issue by xanscale** [angular-schule/vscode-angular-schule-extension-pack#1]
hi, 

i use this extension for is minimal and updated set of dependency choosed.

with the last update dependency set are updated and are very good

but i think that the "Bootstrap 4 snippets" is out of scope because there is many alternative, one for all angular Material from Angular team

so i suggest to remove this dependency 

PS also i suggest to replace robertohuertasm.vscode-icons with pkief.material-icon-theme

**Comment by JohannesHoppe** [comment]
Great to see that the extension is also used outside the scope of our workshops! 😃 

I completely agree. I removed two dependencies
* [Bootstrap 4 snippets](https://marketplace.visualstudio.com/items?itemName=thekalinga.bootstrap4-vscode)
* [Auto Close Tag](https://marketplace.visualstudio.com/items?itemName=formulahendry.auto-close-tag)

The extension can only install deps. So you will have to remove them manually.

**Comment by JohannesHoppe** [comment]
robertohuertasm.vscode-icons vs pkief.material-icon-theme

Can you give me some pros/cons. Or is it just the style?

**Comment by xanscale** [comment]
hi @JohannesHoppe thz for your time

i think that this is the best angular extension pack
 
about icons, i don't know just think material icon theme is more google style :)

PS also i suggest to add a CSS formatter because css is the only "angular" file that vsc not format alone, but i don't know which are better for our scope (css / scss)

**Comment by JohannesHoppe** [comment]
1. Material icons: I really hate this "Project Auto-Detection" prompt (see https://github.com/vscode-icons/vscode-icons/wiki/Pad). I bet this is not existing for "material-icon-theme". Isn't it? But it also wont show a neat "Angular"-icon, if it's a component... (which is super sexy!)
2. CSS formatter -- please review one, i will add it to the next release. I would go for scss.

**Comment by xanscale** [comment]
1) there is no "Project Auto-Detection", and has specific icon for angular (7 different icons for angular)
https://raw.githubusercontent.com/PKief/vscode-material-icon-theme/master/images/fileIcons.png

2) for css i use aeschli.vscode-css-formatter is very simple and minimalistic. no configuration and intercept normal format command

**Comment by JohannesHoppe** [comment]
I'm super busy right now, but this issue is in my TODO list now! 😉
