### ISSUE TITLE
0.4.2 break dependency

### ISSUE THREAD

**Issue by xanscale** [angular-schule/vscode-angular-schule-extension-pack#2]
![screenshot from 2018-06-16 15-17-34](https://user-images.githubusercontent.com/255819/41498902-cae677a8-7178-11e8-9bce-420d1ab13140.png)

**Comment by JohannesHoppe** [comment]
??

**Comment by JohannesHoppe** [comment]
I have no clue what could be wrong?? :-(

**Comment by xanscale** [comment]
does this only happen to me?

**Comment by JohannesHoppe** [comment]
My bad, there was a typo! Please test again!

<img width="1332" alt="screen shot 2018-06-16 at 15 31 40" src="https://user-images.githubusercontent.com/640639/41499047-8f286c92-717a-11e8-9e16-6ca8305fe8bd.png">

**Comment by JohannesHoppe** [comment]
#3 is still open! :-(

(no F1 > Schule > Update...)
