### ISSUE TITLE
TSLint deprecated

### ISSUE THREAD

**Issue by daubor** [angular-schule/vscode-angular-schule-extension-pack#6]
[vscode-tslint](https://marketplace.visualstudio.com/items?itemName=eg2.tslint) is deprecated and replaced by  [vscode-typescript-tslint-plugin](https://marketplace.visualstudio.com/items?itemName=ms-vscode.vscode-typescript-tslint-plugin).

**Comment by JohannesHoppe** [comment]
fixed in v0.4.6, thanks for reporting! 👍
